---
driver:
  name: ec2
  aws_ssh_key_id: learn-chef
  region: us-west-1
  availability_zone: a
  subnet_id: subnet-a73d09c3
  instance_type: t2.micro
  image_id: ami-9c447bfc
  security_group_ids: ["sg-e5b4a682"]
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: ~/.ssh/learn-chef.pem

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[django::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: